import {
  Mail,
  Phone,
  MapPin,
  Github,
  Facebook,
  Instagram,
  X,
  Linkedin,
  Layout,
  Server,
  Lock,
  Code,
  Terminal,
  Smartphone,
  ExternalLink,
} from "lucide-react";

export const IconMap = {
  mail: <Mail />,
  phone: <Phone />,
  location: <MapPin />,
  github: <Github />,
  facebook: <Facebook />,
  instagram: <Instagram />,
  x: <X />,
  linkedin: <Linkedin />,
  Layout: <Layout />,
  Server: <Server />,
  Lock: <Lock />,
  Code: <Code />,
  Terminal: <Terminal />,
  Smartphone: <Smartphone />,
  External: <ExternalLink />,
};
